Add arrow positioning option
bk138/gromit-mpx pull request #143
Opened 2021-10-07 22:06 UTC by natenho

Hello, I've just added this option to draw arrows at either different or both sides of the lines. 

![image](https://user-images.githubusercontent.com/4236481/136467366-16758384-9035-4614-8196-619d4abd6f40.png)
(all lines drawn from left to right)

The configuration is as simple as:

```
"red Marker end" = PEN (size=6 color="red" arrowsize=1 arrowposition="end");    
"red Marker start" = PEN (size=6 color="red" arrowsize=1 arrowposition="start");    
"red Marker both" = PEN (size=6 color="red" arrowsize=1 arrowposition="both");
```

I did it in a single commit because it was not a huge change, let me know whether it doesn't fit the contributing guidelines so I can split it up.

I was looking for a tool which mimics drawing features of [Microsoft ZoomIt](https://docs.microsoft.com/en-us/sysinternals/downloads/zoomit) and gromit seems to be the right tool for that, but it lacks some drawing features that users like me would miss when migrating from Windows environment.

Another feature I want to work on is #67, for the same reason.

2022-01-23 22:11 UTC, bk138 requested changes
First, sorry for the delay, the last months have been pretty wild.

Then, thanks for the contribution! I have a few questions and requests, marked in the patch.

2022-01-23 22:11 UTC, bk138 commented on README.md
> +
Please remove unrelated whitespace changes from the commit. These make it hard to review :-) and can be done in a separate PR.

2022-01-23 22:11 UTC, bk138 commented on data/gromit-mpx.cfg
> +"green Marker" = PEN (size=6 color="green" arrowsize=1 arrowposition="end");
What happens on `green Marker" = PEN (size=6 color="green" arrowsize=1);` ?

2022-01-23 22:11 UTC, bk138 commented on data/gromit-mpx.cfg
> +# Default gromit-mpx configuration
same here wrt the whitespace

2022-01-23 22:11 UTC, bk138 commented on src/callbacks.c
> +/*
please remove unrelated whitespace changes.

2022-01-23 22:11 UTC, bk138 commented on src/callbacks.c
> +					 data->red, 7, 0, GROMIT_ARROW_AT_NONE, 1, G_MAXUINT);
These should probably be  GROMIT_ARROW_AT_END in order to retain the original configless behaviour.

2022-01-23 22:11 UTC, bk138 commented on src/callbacks.c
> +  cleanup_context(devdata->cur_context);
Why was this one added? Can you add an explaining comment please?

2022-01-23 22:11 UTC, bk138 commented on src/config.c
> +  GTokenType token;
This is not used AFAICS.

2022-01-23 22:11 UTC, bk138 commented on src/config.c
> +  name = g_strndup (arroposition_str, len);
This is not used and leaks memory.

2022-01-23 22:11 UTC, bk138 commented on src/config.c
> +  g_scanner_scope_add_symbol (scanner, 2, "size",         (gpointer) 1);
please remove the whitespace change.

2022-01-23 22:11 UTC, bk138 commented on src/config.c
> +                              arrowposition = parse_arrowposition(scanner->value.v_string);
parse_arrowposition() should be inlined as it's got only one caller.

2022-01-23 22:11 UTC, bk138 commented on src/drawing.c
> -typedef struct
Why did this one get removed?

2022-01-23 22:11 UTC, bk138 commented on src/drawing.c
> +
Lotsa whitespace changes that make the real changes harder to spot. Please remove those.

2022-01-23 22:11 UTC, bk138 commented on src/drawing.c
> +  case GROMIT_ARROW_AT_BOTH:
Please add a comment about why these are empty for future code readers.

2022-01-23 22:11 UTC, bk138 commented on src/main.c
> +/*
Please remove the whitespace changes :-)

2022-01-23 22:11 UTC, bk138 commented on src/drawing.c
> +void cleanup_context(GromitPaintContext *context)
That sounds like it's free()-ing the whole context ;-) Maybe clear_context and some comment?

2022-01-23 22:11 UTC, bk138 commented on src/drawing.c
> +void cleanup_context(GromitPaintContext *context)
Actually, just inlining this would be most clear, I think.

2022-01-24 01:52 UTC, natenho commented
@bk138 thanks for your review! Actually I did a lot of changes since this PR that are in my fork, which include features like rectangles, ellipses, and some other some fixes (like fixing some memory leaks I introduced). Currently I'm using gromit-mpx in a daily basis and everything is fine!

I'll try to sync everything back here, but it will probably take a while. Regarding the whitespaces, well, vscode did that. lol.

2022-01-24 06:40 UTC, bk138 commented
> @bk138 thanks for your review! Actually I did a lot of changes since this PR that are in my fork, which include some cool features (based on MIcrosoft ZoomIt) like rectangles, lines, ellipses, and some other some fixes (like fixing some memory leaks I introduced). Currently I'm using my "version of" gromit-mpx in a daily basis and everything is fine!
> 
> I'll try to sync everything back here, but it will probably take a while. Regarding the whitespaces, well, vscode did that. lol. I'll get them fixed aswell.

Super nice - Looking forward to them!

2024-03-08 20:59 UTC, bk138 commented
Closing in favour of #195.

2024-03-08 20:59 UTC, closed without merging