Add Hebrew translation
bk138/gromit-mpx pull request #159
Opened 2022-06-29 14:31 UTC by avma

Add he.po file

2022-06-29 17:42 UTC, bk138 commented
Thanks so much for the contribution! You're almost there, the PR is only missing the build system integration, see https://github.com/bk138/gromit-mpx/blob/master/po/README.md and for how it was done before https://github.com/bk138/gromit-mpx/commits/master/po

2022-06-29 17:44 UTC, bk138 requested changes
CMake integration still to be done.

2022-06-30 17:39 UTC, avma commented
Hope this time I did better...

2022-07-01 09:38 UTC, bk138 requested changes
Thanks so much! Only some really minor cosmetic things left!

2022-07-01 09:38 UTC, bk138 commented on CMakeLists.txt
> +install(FILES ${CMAKE_CURRENT_BINARY_DIR}/he.gmo DESTINATION ${CMAKE_INSTALL_DATADIR}/locale/he/LC_MESSAGES/ RENAME ${LOCALE_DOMAIN}.mo)
please leave the newline before the configure_file stanza in there :-)

2022-07-01 09:38 UTC, bk138 commented on CMakeLists.txt
> +
Please remove that unrelated newline again.

2022-07-02 15:26 UTC, merged