drawing, config, callbacks: add arrowtype option allowing arrow heads…
bk138/gromit-mpx pull request #195
Opened 2024-03-02 15:51 UTC by pascal-niklaus

… at both line ends

Syntax in config file with new option `arrowtype`, which can take values `"->"` (default), `"<-"`, or "`<->`".

Example:

```
"red Pen" = PEN (size=5 color="red", arrowsize=2, arrowtype="->");
"blue Pen" = PEN (color="cyan", size=2, arrowsize=2 arroytype="<->");
"yellow Pen" = LINE (color="yellow" size=2 arrowsize=2 arrowtype="<-");
```

2024-03-08 13:27 UTC, bk138 requested changes
Again, sorry for the long delay, I got held back by other stuff. Also again, thanks for that nice contribution, I have only some minor change requests. 

PS: Don't bother keeping a clean history on the branch, I'll simply squash-merge when ready.

Thanks again!

2024-03-08 13:27 UTC, bk138 commented on src/main.h
> +  GROMIT_ARROW_NONE = 0,
~No need to spell out the enum values here. Please just list the variants.~

2024-03-08 13:27 UTC, bk138 commented on src/main.c
> +        g_printerr(" arrowtype: <- , ");
please use "start", "end", "double" instead of the ASCII arrows here. This makes the intent clearer.

2024-03-08 13:27 UTC, bk138 commented on src/config.c
> +                        {
Please use "start", "end", "double" instead of the ASCII arrows here. This makes the intent clearer.

2024-03-08 13:27 UTC, bk138 commented on src/main.h
> +  GROMIT_ARROW_NONE = 0,
Ah I see you're using this for bitwise comparisons. Can you then add a comment that this is the case and the values shouldn't be changed lightly please.

2024-03-08 15:41 UTC, pascal-niklaus commented
I updated the PR accordingly, now writing the value in the enum as
```
  GROMIT_ARROW_DOUBLE = (GROMIT_ARROW_START | GROMIT_ARROW_END )
```
which should be clear...

2024-03-08 20:34 UTC, bk138 commented on src/main.h
> +  GROMIT_ARROW_DOUBLE = (GROMIT_ARROW_START | GROMIT_ARROW_END )
Yeah this is even more clear, thanks!

2024-03-08 20:35 UTC, bk138 commented
> I updated the PR accordingly, now writing the value in the enum as
> 
> ```
>   GROMIT_ARROW_DOUBLE = (GROMIT_ARROW_START | GROMIT_ARROW_END )
> ```
> 
> which should be clear...



Yeah this is even more clear, thanks!

2024-03-08 20:52 UTC, bk138 commented
One more thing: I noticed that the following minimal config 
```
"red Pen" = PEN (size=5 color="red" arrowtype="double" arrowsize=3);
"default" = "red Pen";
```
does not correctly parse arrowtype.

2024-03-09 07:55 UTC, pascal-niklaus commented
> One more thing: I noticed that the following minimal config
> 
> ```
> "red Pen" = PEN (size=5 color="red" arrowtype="double" arrowsize=3);
> "default" = "red Pen";
> ```
> 
> does not correctly parse arrowtype.

Indeed parsing arrowsize did reset the option to arrowtype=="end", so arrowtype only worked as intended after arrowsize.

Also, I removed ARROW_TYPE_NONE because it was redundant with arrowsize==0. Anyway, arrowsize==0 acts as flag whether there are arrows, and only then is the arrow type tested.

2024-03-11 07:54 UTC, merged

2025-08-07 20:38 UTC, BuddyRaider commented
> One more thing: I noticed that the following minimal config
> 
> ```
> "red Pen" = PEN (size=5 color="red" arrowtype="double" arrowsize=3);
> "default" = "red Pen";
> ```
> 
> does not correctly parse arrowtype.

it seems this issue still exists today, I had a similar tool definition (but with a LINE instead of PEN), and it didn't parse arrowtype until I moved it to the end (I actually didn't think to put it at the end until I saw this quoted reply after doing a search through the issues and PRs)